/*
	Autore: Gabriele Franco
	Descrizione: JSON in SQL SERVER 2019: Setup
*/

USE [tempdb]
GO

CREATE DATABASE JSON_DEMO
GO

USE JSON_DEMO
GO

DROP TABLE IF EXISTS dbo.UTENTI
DROP TABLE IF EXISTS dbo.UTENTI_NUMERI
DROP TABLE IF EXISTS dbo.UTENTI_JSON
DROP TABLE IF EXISTS dbo.TEST_JSON_DATA_SCHEMALESS
GO

DROP SEQUENCE IF EXISTS SQ_UTENTI_ID_UTENTE
DROP SEQUENCE IF EXISTS SQ_UTENTI_NUMERI_ID_UTENTE_NUMERO
DROP SEQUENCE IF EXISTS SQ_UTENTI_JSON_ID_UTENTE
DROP SEQUENCE IF EXISTS SQ_TEST_JSON_DATA_SCHEMALESS_ID
GO


CREATE SEQUENCE SQ_UTENTI_ID_UTENTE
AS int
	START WITH 1
	INCREMENT BY 1
	CACHE 1000
	NO CYCLE
GO

CREATE SEQUENCE SQ_UTENTI_NUMERI_ID_UTENTE_NUMERO
AS int
	START WITH 1
	INCREMENT BY 1
	CACHE 1000
	NO CYCLE
GO

CREATE SEQUENCE SQ_UTENTI_JSON_ID_UTENTE
AS int
	START WITH 1
	INCREMENT BY 1
	CACHE 1000
	NO CYCLE
GO

CREATE TABLE dbo.UTENTI
(
	ID_UTENTE		 int NOT NULL CONSTRAINT DF_UTENTI_ID_UTENTE DEFAULT NEXT VALUE FOR [dbo].[SQ_UTENTI_ID_UTENTE]
	,USERNAME		 varchar(100) NOT NULL  
	,NOME			 varchar(100) NOT NULL
	,COGNOME	     varchar(100) NOT NULL
	,DATA_DI_NASCITA datetime2(0) NOT NULL
	,CONSTRAINT [PK_UTENTI] PRIMARY KEY CLUSTERED 
	 (
		ID_UTENTE ASC
	 )
	,CONSTRAINT [UX_UTENTI_USERNAME] UNIQUE 
	 (
		USERNAME ASC
     )
)
GO

INSERT INTO dbo.UTENTI (USERNAME, NOME, COGNOME, DATA_DI_NASCITA) VALUES 
('Gabry', 'Gabriele', 'Franco', '1990-01-01')
,('Jack', 'Giacomo', 'Gizzi', '1980-01-01')
,('MartinPa', 'Martin', 'Pozzi', '1970-01-01')

CREATE TABLE  dbo.UTENTI_NUMERI
(
	ID_UTENTE_NUMERO int NOT NULL CONSTRAINT DF_UTENTI_NUMERI_ID_UTENTE_NUMERO DEFAULT NEXT VALUE FOR [dbo].[SQ_UTENTI_NUMERI_ID_UTENTE_NUMERO]
	,ID_UTENTE int NOT NULL
	,TIPO      varchar (100) NOT NULL
	,TELEFONO  varchar(100) NOT NULL
	,CONSTRAINT [FK_UTENTI_NUMERI_UTENTI] FOREIGN KEY (ID_UTENTE)
	 REFERENCES dbo.UTENTI (ID_UTENTE)
	,CONSTRAINT [PK_UUTENTI_NUMERI] PRIMARY KEY CLUSTERED  
	 (
		ID_UTENTE_NUMERO ASC
     )
)

INSERT INTO dbo.UTENTI_NUMERI (ID_UTENTE, TIPO, TELEFONO) VALUES 
(1, 'UFFICIO', '3409094543'), (1, 'PERSONALE', '3409094544')
,(2, 'UFFICIO', '3499094543'), (2, 'PERSONALE', '3499094544')
,(3, 'UFFICIO', '3489094543'), (3, 'PERSONALE', '3489094544')

CREATE TABLE dbo.UTENTI_JSON
(
	ID_UTENTE int NOT NULL CONSTRAINT DF_UTENTI_JSON_ID_UTENTE DEFAULT NEXT VALUE FOR [dbo].[SQ_UTENTI_JSON_ID_UTENTE]
	,JSON_DATA varchar(1000) NOT NULL CONSTRAINT [CK_JSON_DATA] CHECK(ISJSON(JSON_DATA) = 1)
	,CONSTRAINT [PK_UTENTI_JSON] PRIMARY KEY CLUSTERED (ID_UTENTE ASC)
	--,INDEX cci CLUSTERED COLUMNSTORE
) --WITH (DATA_COMPRESSION = PAGE)
GO

INSERT INTO dbo.UTENTI_JSON (JSON_DATA) VALUES 
('{
    "ID_UTENTE": 1,
    "USERNAME": "Gabry",
    "NOME": "Gabriele",
    "COGNOME": "Franco",
    "DATA_DI_NASCITA": "1990-01-01T00:00:00",
    "UTENTI_NUMERI": [
      {
        "ID_UTENTE_NUMERO": 1,
        "TIPO": "UFFICIO",
        "TELEFONO": "3409094543"
      },
      {
        "ID_UTENTE_NUMERO": 2,
        "TIPO": "PERSONALE",
        "TELEFONO": "3409094544"
      }
    ]
  }')
  ,('{
    "ID_UTENTE": 2,
    "USERNAME": "Jack",
    "NOME": "Giacomo",
    "COGNOME": "Gizzi",
    "DATA_DI_NASCITA": "1980-01-01T00:00:00",
    "UTENTI_NUMERI": [
      {
        "ID_UTENTE_NUMERO": 3,
        "TIPO": "UFFICIO",
        "TELEFONO": "3499094443"
      },
      {
        "ID_UTENTE_NUMERO": 4,
        "TIPO": "PERSONALE",
        "TELEFONO": "3499094544"
      }
    ]
  }')
  ,('{
    "ID_UTENTE": 3,
    "USERNAME": "MartinPa",
    "NOME": "Martin",
    "COGNOME": "Pozzi",
    "DATA_DI_NASCITA": "1970-01-01T00:00:00",
    "UTENTI_NUMERI": [
      {
        "ID_UTENTE_NUMERO": 5,
        "TIPO": "UFFICIO",
        "TELEFONO": "3489094543"
      },
      {
        "ID_UTENTE_NUMERO": 6,
        "TIPO": "PERSONALE",
        "TELEFONO": "3489094544"
      }
    ]
  }')
GO

CREATE SEQUENCE [dbo].[SQ_TEST_JSON_DATA_SCHEMALESS_ID]
AS int
	START WITH 1
	INCREMENT BY 1
	CACHE 1000
	NO CYCLE
GO

CREATE TABLE dbo.TEST_JSON_DATA_SCHEMALESS
(
	ID int NOT NULL CONSTRAINT DF_TEST_JSON_DATA_SCHEMALESS_ID DEFAULT NEXT VALUE FOR [dbo].[SQ_TEST_JSON_DATA_SCHEMALESS_ID]
	,JSON_DATA varchar(4000) NOT NULL CONSTRAINT [CK_TEST_JSON_DATA_SCHEMALESS_JSON_DATA] CHECK(ISJSON(JSON_DATA) = 1)
	,CONSTRAINT [PK_TEST_JSON_DATA_SCHEMALESS] PRIMARY KEY CLUSTERED (ID ASC)
	--,INDEX cci CLUSTERED COLUMNSTORE
) --WITH (DATA_COMPRESSION = PAGE)
GO

--EXEC sp_help 'dbo.UTENTI'
--EXEC sp_help 'dbo.UTENTI_NUMERI'
--EXEC sp_help 'dbo.UTENTI_JSON'

