/*
	Autore: Gabriele Franco
	Descrizione: JSON in SQL SERVER 2019: Clustered columnstore index 
*/
USE JSON_DEMO
GO

DROP TABLE IF EXISTS [dbo].[TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE]
GO

SELECT *, --JSON_DATA_EXTRA = JSON_DATA + JSON_DATA + JSON_DATA + JSON_DATA + JSON_DATA 
INTO [dbo].[TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE]
FROM [dbo].[TEST_JSON_DATA_SCHEMALESS] 

EXEC sp_spaceused '[dbo].[TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE]' 

CREATE CLUSTERED COLUMNSTORE INDEX CCIX_TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE ON dbo.TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE
WITH (MAXDOP = 4)

EXEC sp_spaceused '[dbo].[TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE]'

CREATE CLUSTERED COLUMNSTORE INDEX CCIX_TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE ON dbo.TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE
WITH (MAXDOP = 4, DATA_COMPRESSION = COLUMNSTORE_ARCHIVE, DROP_EXISTING = ON)

EXEC sp_spaceused '[dbo].[TEST_JSON_DATA_SCHEMALESS_COLUMNSTORE]'

