/*
	Autore: Gabriele Franco
	Descrizione: JSON in SQL SERVER 2019: ISJSON
*/

USE JSON_DEMO
GO

SELECT * FROM dbo.UTENTI
SELECT * FROM dbo.UTENTI_NUMERI
SELECT * FROM dbo.UTENTI_JSON


--ISJSON (SI PUO' USARE ANCHE COME CONSTRAINT)
SELECT 
	ID_UTENTE
	,JSON_DATA
FROM 
	dbo.UTENTI_JSON
WHERE ISJSON(JSON_DATA) = 1


--TEST FUNCTION ISJSON
ALTER TABLE [dbo].[UTENTI_JSON] DROP CONSTRAINT [CK_JSON_DATA]
GO

INSERT INTO dbo.UTENTI_JSON (JSON_DATA) VALUES 
(N'4
  {
    "ID_UTENTE": 1,
    "USERNAME": "Gabry",
    "NOME": "Gabriele",
    "COGNOME": "Franco",
    "DATA_DI_NASCITA": "1990-01-01T00:00:00",
    "UTENTI_NUMERI": [
      {
        "ID_UTENTE_NUMERO": 1,
        "ID_UTENTE": 1,
        "TIPO": "UFFICIO",
        "TELEFONO": "3409094543"
      },
      {
        "ID_UTENTE_NUMERO": 2,
        "ID_UTENTE": 1,
        "TIPO": "PERSONALE",
        "TELEFONO": "3409094544"
      }
    ]
  }')

--RIAGGIUNGO CONSTRAINT E DARA' ERRORE
ALTER TABLE [dbo].[UTENTI_JSON]  WITH CHECK ADD CONSTRAINT [CK_JSON_DATA] CHECK ((ISJSON([JSON_DATA])=(1)))
GO

--PRENDO LA RIGA IN ERRORE 
SELECT 
	ID_UTENTE
	,JSON_DATA
FROM 
	dbo.UTENTI_JSON
WHERE ISJSON(JSON_DATA) = 0 

--CORREZIONE RIGA JSON ERRATA
UPDATE dbo.UTENTI_JSON
SET 
	JSON_DATA = '{
					"ID_UTENTE": 1,
					"USERNAME": "Gabry",
					"NOME": "Gabriele",
					"COGNOME": "Franco",
					"DATA_DI_NASCITA": "1990-01-01T00:00:00",
					"UTENTI_NUMERI": [
					  {
						"ID_UTENTE_NUMERO": 1,
						"ID_UTENTE": 1,
						"TIPO": "UFFICIO",
						"TELEFONO": "3409094543"
					  },
					  {
						"ID_UTENTE_NUMERO": 2,
						"ID_UTENTE": 1,
						"TIPO": "PERSONALE",
						"TELEFONO": "3409094544"
					  }
					]
				  }'
WHERE ID_UTENTE = 4

--RIAGGIUNGO CONSTRAINT CORRETTAMENTE
ALTER TABLE [dbo].[UTENTI_JSON]  WITH CHECK ADD CONSTRAINT [CK_JSON_DATA] CHECK ((ISJSON([JSON_DATA])=(1)))
GO
ALTER TABLE [dbo].[UTENTI_JSON] CHECK CONSTRAINT [CK_JSON_DATA]
GO

DELETE dbo.UTENTI_JSON WHERE ID_UTENTE = 4