/*
	Autore: Gabriele Franco
	Descrizione: JSON in SQL SERVER 2019: JSON_VALUE, JSON_QUERY, LAX E STRICT
*/

USE JSON_DEMO
GO

--1 Uso di JSON_VALUE e JSON_QUERY 
SELECT 
	ID_UTENTE
	,NOME = JSON_VALUE(JSON_DATA, '$.NOME') 
	,COGNOME = JSON_VALUE(JSON_DATA, '$.COGNOME')
	,USERNAME = JSON_VALUE(JSON_DATA,'$.USERNAME')
	,NUMERI = JSON_QUERY(JSON_DATA, '$.UTENTI_NUMERI')
	,JSON_DATA --usa https://jsonformatter.org/ per formattare il JSON
FROM
	dbo.UTENTI_JSON
WHERE
	JSON_VALUE(JSON_DATA, 'lax $.NOME') = N'Gabriele'


--2 Uso di JSON_VALUE e JSON_QUERY con lax e strict

--Se il property path è errato con lax restituisce null nella selezione di una colonna 
SELECT 
	ID_UTENTE
	,NOME = JSON_VALUE(JSON_DATA, 'lax $.NOMEE') --COLONNA ERRATA
	,COGNOME = JSON_VALUE(JSON_DATA, 'lax $.COGNOME')
	,USERNAME = JSON_VALUE(JSON_DATA,' lax $.USERNAME')
	,NUMERI = JSON_QUERY(JSON_DATA, 'lax $.UTENTI_NUMERI')
	,JSON_DATA
FROM
	dbo.UTENTI_JSON
WHERE
	JSON_VALUE(JSON_DATA, 'lax $.NOME') = N'Gabriele'

--Se il property path è errato con lax restituisce 0 record se usato come filtro
SELECT 
	ID_UTENTE
	,NOME = JSON_VALUE(JSON_DATA, 'lax $.NOME')
	,COGNOME = JSON_VALUE(JSON_DATA, 'lax $.COGNOME')
	,USERNAME = JSON_VALUE(JSON_DATA,' lax $.USERNAME')
	,NUMERI = JSON_QUERY(JSON_DATA, 'lax $.UTENTI_NUMERI')
	,JSON_DATA
FROM
	dbo.UTENTI_JSON
WHERE
	JSON_VALUE(JSON_DATA, 'lax $.NOMEE') = N'Gabriele' --FILTRO ERRATO
 
--Con Strinct in entrambi i casi restituisce errore
SELECT 
	ID_UTENTE
	,NOME = JSON_VALUE(JSON_DATA, 'strict $.NOMEE') --COLONNA ERRATA
	,COGNOME = JSON_VALUE(JSON_DATA, 'lax $.COGNOME')
	,USERNAME = JSON_VALUE(JSON_DATA,' lax $.USERNAME')
	,NUMERI = JSON_QUERY(JSON_DATA, 'lax $.UTENTI_NUMERI')
	,JSON_DATA
FROM
	dbo.UTENTI_JSON
WHERE
	JSON_VALUE(JSON_DATA, 'strict $.NOMEE') = N'Gabriele' --FILTRO ERRATO


--3 Uso di una CTE con JSON_VALUE e JSON_QUERY
;WITH CTE AS (
	SELECT 
		ID_UTENTE
		,NOME = JSON_VALUE(JSON_DATA, '$.NOME')
		,COGNOME = JSON_VALUE(JSON_DATA, '$.COGNOME')
		,USERNAME = JSON_VALUE(JSON_DATA, '$.USERNAME')
		,NUMERI = JSON_QUERY(JSON_DATA, '$.UTENTI_NUMERI')
		,JSON_DATA
	FROM
		dbo.UTENTI_JSON
	WHERE
		JSON_VALUE(JSON_DATA, '$.NOME') = N'GABRIELE'		
)
SELECT 
	NOME
	,COGNOME
	,USERNAME
	,TIPO = JSON_VALUE(NUMERI,'$[0].TIPO')
	,NUMERO = JSON_VALUE(NUMERI,'$[0].TELEFONO')
	,TIPO = JSON_VALUE(NUMERI,'$[1].TIPO')
	,NUMERO = JSON_VALUE(NUMERI,'$[1].TELEFONO')
FROM
	CTE 



